#Runs all the tests! Triggers on push and PR for quick feedback.
#Tests are not very comprehensive right now, so don't put too much faith in this.
name: run tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871

      - name: Set up Go
        uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Install Tools
        run: make prep

      - name: Execute tests
        run: make test && make testacc

      - name: Upload test artifacts for debugging
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882
        if: failure()
        with:
          name: test-debug-artifacts
          path: |
            datasource/*/git_*_basic_test.pkr.hcl
            datasource/*/packer_log_git_*_basic_test.txt
          if-no-files-found: ignore
